package senegal.chercher.emploi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LocalisationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalisationAllPropertiesEquals(Localisation expected, Localisation actual) {
        assertLocalisationAutoGeneratedPropertiesEquals(expected, actual);
        assertLocalisationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalisationAllUpdatablePropertiesEquals(Localisation expected, Localisation actual) {
        assertLocalisationUpdatableFieldsEquals(expected, actual);
        assertLocalisationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalisationAutoGeneratedPropertiesEquals(Localisation expected, Localisation actual) {
        assertThat(actual)
            .as("Verify Localisation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalisationUpdatableFieldsEquals(Localisation expected, Localisation actual) {
        assertThat(actual)
            .as("Verify Localisation relevant properties")
            .satisfies(a -> assertThat(a.getRegion()).as("check region").isEqualTo(expected.getRegion()))
            .satisfies(a -> assertThat(a.getDepartement()).as("check departement").isEqualTo(expected.getDepartement()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalisationUpdatableRelationshipsEquals(Localisation expected, Localisation actual) {
        // empty method
    }
}
