package senegal.chercher.emploi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PosteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosteAllPropertiesEquals(Poste expected, Poste actual) {
        assertPosteAutoGeneratedPropertiesEquals(expected, actual);
        assertPosteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosteAllUpdatablePropertiesEquals(Poste expected, Poste actual) {
        assertPosteUpdatableFieldsEquals(expected, actual);
        assertPosteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosteAutoGeneratedPropertiesEquals(Poste expected, Poste actual) {
        assertThat(actual)
            .as("Verify Poste auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosteUpdatableFieldsEquals(Poste expected, Poste actual) {
        assertThat(actual)
            .as("Verify Poste relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosteUpdatableRelationshipsEquals(Poste expected, Poste actual) {
        // empty method
    }
}
